In [1]:
import numpy as np
from numpy import shape

from datetime import date

import random
import math
import dill
import glob
import gc

# from tensorflow import keras

import matplotlib.pyplot as plt

import tensorflow as tf

from random import seed

# Import train_test_split function
from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow import device

# Tensorflow soll auf CPU und nicht auf der GPU laufen
device("cpu:0")

# für GPU:
# tf.device("gpu:0")

2022-09-16 13:42:55.659991: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-16 13:42:55.660022: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-09-16 13:42:56.880375: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-09-16 13:42:56.880408: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-16 13:42:56.880428: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (8141ff0cdda3): /proc/driver/nvidia/version does not exist


2022-09-16 13:42:56.880668: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
%run '../../_functions/functions.py'

### Load images

In [6]:
# Import data that was saved on this system

raw_data = load_file(file = "../data/raw_data/raw_images_and_labels.pkl")
X = raw_data[0]
y = raw_data[1]

# Factorize into dichotomous variable
Y = pd.factorize(y)[0]

np.unique(y, return_counts=True)

(array([0, 8]), array([178, 174]))

### Load Persistences Landscapes

In [7]:
pl_folderpath = "../data/persistence_landscapes_averages/"

In [8]:
# Eingelesenen Dateien
print(glob.glob(pl_folderpath + "avgPL_bucket01_H0_scaledWithin*.pkl")[-1])
print(glob.glob(pl_folderpath + "avgPL_bucket01_H1_scaledWithin*.pkl")[-1])
print(glob.glob(pl_folderpath + "avgPL_bucket01_H0_scaledBetween*.pkl")[-1])
print(glob.glob(pl_folderpath + "avgPL_bucket01_H1_scaledBetween*.pkl")[-1])
print(glob.glob(pl_folderpath + "avgPL_bucket01_H0_unscaled*.pkl")[-1])
print(glob.glob(pl_folderpath + "avgPL_bucket01_H1_unscaled*.pkl")[-1])

../data/persistence_landscapes_averages/avgPL_bucket01_H0_scaledWithin_2022-09-16.pkl
../data/persistence_landscapes_averages/avgPL_bucket01_H1_scaledWithin_2022-09-16.pkl
../data/persistence_landscapes_averages/avgPL_bucket01_H0_scaledBetween_2022-09-16.pkl
../data/persistence_landscapes_averages/avgPL_bucket01_H1_scaledBetween_2022-09-16.pkl
../data/persistence_landscapes_averages/avgPL_bucket01_H0_unscaled_2022-09-16.pkl
../data/persistence_landscapes_averages/avgPL_bucket01_H1_unscaled_2022-09-16.pkl


In [9]:
avgPL_bucket01_H0_scaledWithin = load_file(file = glob.glob(pl_folderpath + "avgPL_bucket01_H0_scaledWithin*.pkl")[-1])
avgPL_bucket01_H1_scaledWithin = load_file(file = glob.glob(pl_folderpath + "avgPL_bucket01_H1_scaledWithin*.pkl")[-1])

avgPL_bucket01_H0_scaledBetween = load_file(file = glob.glob(pl_folderpath + "avgPL_bucket01_H0_scaledBetween*.pkl")[-1])
avgPL_bucket01_H1_scaledBetween = load_file(file = glob.glob(pl_folderpath + "avgPL_bucket01_H1_scaledBetween*.pkl")[-1])

avgPL_bucket01_H0_unscaled = load_file(file = glob.glob(pl_folderpath + "avgPL_bucket01_H0_unscaled*.pkl")[-1])
avgPL_bucket01_H1_unscaled = load_file(file = glob.glob(pl_folderpath + "avgPL_bucket01_H1_unscaled*.pkl")[-1])

In [10]:
# Parameter for persistence landscapes
pl_resolution = 250
pl_num_landscapes = 10

### Train-Test-Splits Persistence Landscapes

In [11]:
relevant_samples = len(avgPL_bucket01_H0_scaledBetween)
relevant_samples

352

In [12]:
# Bucket01 scaledBetween
seed(999)
# Train-Test-Split 
X_b01_scaledBetween_H0_train, X_b01_scaledBetween_H0_test, Y_b01_scaledBetween_H0_train, Y_b01_scaledBetween_H0_test = train_test_split(avgPL_bucket01_H0_scaledBetween,
                                                                                                                                        Y,
                                                                                                                                        test_size=0.2)

seed(999)
# Train-Test-Split 
X_b01_scaledBetween_H1_train, X_b01_scaledBetween_H1_test, Y_b01_scaledBetween_H1_train, Y_b01_scaledBetween_H1_test = train_test_split(avgPL_bucket01_H1_scaledBetween,
                                                                                                                                        Y,
                                                                                                                                        test_size=0.2)

# Bucket01 scaledWithin
seed(999)
# Train-Test-Split 
X_b01_scaledWithin_H0_train, X_b01_scaledWithin_H0_test, Y_b01_scaledWithin_H0_train, Y_b01_scaledWithin_H0_test = train_test_split(avgPL_bucket01_H0_scaledWithin,
                                                                                                                                    Y,
                                                                                                                                    test_size=0.2)
seed(999)
# Train-Test-Split 
X_b01_scaledWithin_H1_train, X_b01_scaledWithin_H1_test, Y_b01_scaledWithin_H1_train, Y_b01_scaledWithin_H1_test = train_test_split(avgPL_bucket01_H1_scaledWithin,
                                                                                                                                    Y,
                                                                                                                                    test_size=0.2)

# Bucket01 Unscaled
seed(999)
# Train-Test-Split 
X_b01_unscaled_H0_train, X_b01_unscaled_H0_test, Y_b01_unscaled_H0_train, Y_b01_unscaled_H0_test = train_test_split(avgPL_bucket01_H0_unscaled,
                                                                                                                    Y,
                                                                                                                    test_size=0.2)
seed(999)
# Train-Test-Split 
X_b01_unscaled_H1_train, X_b01_unscaled_H1_test, Y_b01_unscaled_H1_train, Y_b01_unscaled_H1_test = train_test_split(avgPL_bucket01_H1_unscaled,
                                                                                                                    Y,
                                                                                                                    test_size=0.2)

# Machine Learning Classification

## Support Vector Machine

In [15]:
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [16]:
folderpath_results = "../results/"

In [17]:
# Train-test split with data in vector format
image_vector_size = 8*8

X_raw_train, X_raw_test, y_raw_train, y_raw_test = train_test_split(X.reshape(len(X), image_vector_size),
                                                                    np.asarray(y),
                                                                    test_size = 0.3,
                                                                    random_state = 2)

##### SVM (raw data)

In [19]:
# Linear - Rawdata
clf = make_pipeline(StandardScaler(), 
                    SVC(kernel='linear')).fit(X_raw_train, y_raw_train.ravel())

print("Accuracy SVM on raw data: " + str(clf.score(X_raw_test, y_raw_test))[:10])

evaluation(y_test = y_raw_test,
           y_pred = clf.predict(X_raw_test),
           filename_csv = folderpath_results + "svm_linear_rawdata.csv")

Accuracy SVM on raw data: 1.0
Confusion-Matrix:
 [[49  0]
 [ 0 57]] 
 
True Negative:  49 
True Positive 57 
False Negative 0 
False Positive 0

TPR: 1.0 
TNR:  1.0

Accuracy: 1.0
F1 (micro): 1.0
F1 (macro): 1.0


In [20]:
# RBF - Rawdata
clf = make_pipeline(StandardScaler(), 
                    SVC(kernel='rbf')).fit(X_raw_train, y_raw_train.ravel())

print("Accuracy SVM on raw data: " + str(clf.score(X_raw_test, y_raw_test))[:10])

evaluation(y_test = y_raw_test,
           y_pred = clf.predict(X_raw_test),
           filename_csv = folderpath_results + "svm_rbf_rawdata.csv")

Accuracy SVM on raw data: 1.0
Confusion-Matrix:
 [[49  0]
 [ 0 57]] 
 
True Negative:  49 
True Positive 57 
False Negative 0 
False Positive 0

TPR: 1.0 
TNR:  1.0

Accuracy: 1.0
F1 (micro): 1.0
F1 (macro): 1.0


##### SVM (Persistent Landscapes - scaledWithin)

In [22]:
# Linear - H0 - scaledWithin
clf_pl_h0 = make_pipeline(StandardScaler(), 
                       SVC(kernel='linear')).fit(X_b01_scaledWithin_H0_train, Y_b01_scaledWithin_H0_train)

print("Accuracy SVM on peristence landscapes (scaled within sample): " + str(clf_pl_h0.score(X_b01_scaledWithin_H0_test, Y_b01_scaledWithin_H0_test))[:10])

evaluation(y_test = Y_b01_scaledWithin_H0_test,
           y_pred = clf_pl_h0.predict(X_b01_scaledWithin_H0_test),
           filename_csv = folderpath_results + "svm_linear_H0_scaledWithin.csv")

Accuracy SVM on peristence landscapes (scaled within sample): 0.53521126
Confusion-Matrix:
 [[22  8]
 [25 16]] 
 
True Negative:  22 
True Positive 16 
False Negative 25 
False Positive 8

TPR: 0.3902439024390244 
TNR:  0.7333333333333333

Accuracy: 0.5352112676056338
F1 (micro): 0.5352112676056338
F1 (macro): 0.5318681318681319


In [23]:
# Linear - H1 - scaledWithin
clf_pl = make_pipeline(StandardScaler(), 
                       SVC(kernel='linear')).fit(X_b01_scaledWithin_H1_train, Y_b01_scaledWithin_H1_train)

print("Accuracy SVM on peristence landscapes (scaled within sample): " + str(clf_pl.score(X_b01_scaledWithin_H1_test, Y_b01_scaledWithin_H1_test))[:10])

evaluation(y_test = Y_b01_scaledWithin_H1_test,
           y_pred = clf_pl.predict(X_b01_scaledWithin_H1_test),
           filename_csv = folderpath_results + "svm_linear_H1_scaledWithin.csv")

Accuracy SVM on peristence landscapes (scaled within sample): 0.52112676
Confusion-Matrix:
 [[18 19]
 [15 19]] 
 
True Negative:  18 
True Positive 19 
False Negative 15 
False Positive 19

TPR: 0.5588235294117647 
TNR:  0.4864864864864865

Accuracy: 0.5211267605633803
F1 (micro): 0.5211267605633803
F1 (macro): 0.5210317460317461


In [24]:
# RBF - H0 - scaledWithin
clf_pl_h0 = make_pipeline(StandardScaler(), 
                       SVC(kernel='rbf')).fit(X_b01_scaledWithin_H0_train, Y_b01_scaledWithin_H0_train)

print("Accuracy SVM on peristence landscapes (scaled within sample): " + str(clf_pl_h0.score(X_b01_scaledWithin_H0_test, Y_b01_scaledWithin_H0_test))[:10])

evaluation(y_test = Y_b01_scaledWithin_H0_test,
           y_pred = clf_pl_h0.predict(X_b01_scaledWithin_H0_test),
           filename_csv = folderpath_results + "svm_rbf_H0_scaledWithin.csv")

Accuracy SVM on peristence landscapes (scaled within sample): 0.59154929
Confusion-Matrix:
 [[19 11]
 [18 23]] 
 
True Negative:  19 
True Positive 23 
False Negative 18 
False Positive 11

TPR: 0.5609756097560976 
TNR:  0.6333333333333333

Accuracy: 0.5915492957746479
F1 (micro): 0.5915492957746479
F1 (macro): 0.5902487562189054


In [25]:
# RBF - H1 - scaledWithin
clf_pl_rbf = make_pipeline(StandardScaler(), 
                       SVC(kernel='rbf')).fit(X_b01_scaledWithin_H1_train, Y_b01_scaledWithin_H1_train)

print("Accuracy SVM on peristence landscapes (scaled within sample): " + str(clf_pl_rbf.score(X_b01_scaledWithin_H1_test, Y_b01_scaledWithin_H1_test))[:10])

evaluation(y_test = Y_b01_scaledWithin_H1_test,
           y_pred = clf_pl_rbf.predict(X_b01_scaledWithin_H1_test),
           filename_csv = folderpath_results + "svm_rbf_H1_scaledWithin.csv")

Accuracy SVM on peristence landscapes (scaled within sample): 0.54929577
Confusion-Matrix:
 [[12 25]
 [ 7 27]] 
 
True Negative:  12 
True Positive 27 
False Negative 7 
False Positive 25

TPR: 0.7941176470588235 
TNR:  0.32432432432432434

Accuracy: 0.5492957746478874
F1 (micro): 0.5492957746478874
F1 (macro): 0.5282392026578073


##### SVM (Persistent Landscapes - scaledBetween)

In [26]:
# Linear - H0 - scaledBetween
clf_pl = make_pipeline(StandardScaler(), 
                    SVC(kernel='linear')).fit(X_b01_scaledBetween_H0_train, Y_b01_scaledBetween_H0_train)

print("Accuracy SVM : " + str(clf_pl.score(X_b01_scaledBetween_H0_test, Y_b01_scaledBetween_H0_test))[:10])

evaluation(y_test = Y_b01_scaledBetween_H0_test,
           y_pred = clf_pl.predict(X_b01_scaledBetween_H0_test),
           filename_csv = folderpath_results + "svm_linear_H0_scaledBetween.csv")

Accuracy SVM : 0.54929577
Confusion-Matrix:
 [[23 14]
 [18 16]] 
 
True Negative:  23 
True Positive 16 
False Negative 18 
False Positive 14

TPR: 0.47058823529411764 
TNR:  0.6216216216216216

Accuracy: 0.5492957746478874
F1 (micro): 0.5492957746478874
F1 (macro): 0.5448717948717949


In [27]:
# Linear - H1 - scaledBetween
clf_pl = make_pipeline(StandardScaler(), 
                    SVC(kernel='linear')).fit(X_b01_scaledBetween_H1_train, Y_b01_scaledBetween_H1_train)

print("Accuracy SVM : " + str(clf_pl.score(X_b01_scaledBetween_H1_test, Y_b01_scaledBetween_H1_test))[:10])

evaluation(y_test = Y_b01_scaledBetween_H1_test,
           y_pred = clf_pl.predict(X_b01_scaledBetween_H1_test),
           filename_csv = folderpath_results + "svm_linear_H1_scaledBetween.csv")

Accuracy SVM : 0.50704225
Confusion-Matrix:
 [[22 12]
 [23 14]] 
 
True Negative:  22 
True Positive 14 
False Negative 23 
False Positive 12

TPR: 0.3783783783783784 
TNR:  0.6470588235294118

Accuracy: 0.5070422535211268
F1 (micro): 0.5070422535211268
F1 (macro): 0.5007032348804501


In [28]:
# RBF - H0 - scaledBetween
clf_pl = make_pipeline(StandardScaler(), 
                    SVC(kernel='rbf')).fit(X_b01_scaledBetween_H0_train, Y_b01_scaledBetween_H0_train)

print("Accuracy SVM : " + str(clf_pl.score(X_b01_scaledBetween_H0_test, Y_b01_scaledBetween_H0_test))[:10])

evaluation(y_test = Y_b01_scaledBetween_H0_test,
           y_pred = clf_pl.predict(X_b01_scaledBetween_H0_test),
           filename_csv = folderpath_results + "svm_rbf_H0_scaledBetween.csv")

Accuracy SVM : 0.57746478
Confusion-Matrix:
 [[17 20]
 [10 24]] 
 
True Negative:  17 
True Positive 24 
False Negative 10 
False Positive 20

TPR: 0.7058823529411765 
TNR:  0.4594594594594595

Accuracy: 0.5774647887323944
F1 (micro): 0.5774647887323944
F1 (macro): 0.5733173076923077


In [29]:
# RBF - H1 - scaledBetween
clf_pl_rbf = make_pipeline(StandardScaler(), 
                    SVC(kernel='rbf')).fit(X_b01_scaledBetween_H1_train, Y_b01_scaledBetween_H1_train)

print("Accuracy SVM : " + str(clf_pl_rbf.score(X_b01_scaledBetween_H1_test, Y_b01_scaledBetween_H1_test))[:10])

evaluation(y_test = Y_b01_scaledBetween_H1_test,
           y_pred = clf_pl_rbf.predict(X_b01_scaledBetween_H1_test),
           filename_csv = folderpath_results + "svm_rbf_H1_scaledBetween.csv")

Accuracy SVM : 0.57746478
Confusion-Matrix:
 [[22 12]
 [18 19]] 
 
True Negative:  22 
True Positive 19 
False Negative 18 
False Positive 12

TPR: 0.5135135135135135 
TNR:  0.6470588235294118

Accuracy: 0.5774647887323944
F1 (micro): 0.5774647887323944
F1 (macro): 0.5767090620031796


##### SVM (Persistent Landscapes - unscaled)

In [30]:
# Linear - H0 - unscaled
clf_pl = make_pipeline(StandardScaler(), 
                    SVC(kernel='linear')).fit(X_b01_unscaled_H0_train, Y_b01_unscaled_H0_train)

print("Accuracy SVM : " + str(clf_pl.score(X_b01_unscaled_H0_test, Y_b01_unscaled_H0_test))[:10])

evaluation(y_test = Y_b01_unscaled_H0_test,
           y_pred = clf_pl.predict(X_b01_unscaled_H0_test),
           filename_csv = folderpath_results + "svm_linear_H0_unscaled.csv")

Accuracy SVM : 0.64788732
Confusion-Matrix:
 [[17 16]
 [ 9 29]] 
 
True Negative:  17 
True Positive 29 
False Negative 9 
False Positive 16

TPR: 0.7631578947368421 
TNR:  0.5151515151515151

Accuracy: 0.647887323943662
F1 (micro): 0.647887323943662
F1 (macro): 0.6375331835817848


In [31]:
# Linear - H1 - unscaled
clf_pl = make_pipeline(StandardScaler(), 
                    SVC(kernel='linear')).fit(X_b01_unscaled_H1_train, Y_b01_unscaled_H1_train)

print("Accuracy SVM : " + str(clf_pl.score(X_b01_unscaled_H1_test, Y_b01_unscaled_H1_test))[:10])

evaluation(y_test = Y_b01_unscaled_H1_test,
           y_pred = clf_pl.predict(X_b01_unscaled_H1_test),
           filename_csv = folderpath_results + "svm_linear_H1_unscaled.csv")

Accuracy SVM : 0.52112676
Confusion-Matrix:
 [[15 24]
 [10 22]] 
 
True Negative:  15 
True Positive 22 
False Negative 10 
False Positive 24

TPR: 0.6875 
TNR:  0.38461538461538464

Accuracy: 0.5211267605633803
F1 (micro): 0.5211267605633803
F1 (macro): 0.5164262820512822


In [32]:
# RBF - H0 - unscaled
clf_pl = make_pipeline(StandardScaler(), 
                    SVC(kernel='rbf')).fit(X_b01_unscaled_H0_train, Y_b01_unscaled_H0_train)

print("Accuracy SVM : " + str(clf_pl.score(X_b01_unscaled_H0_test, Y_b01_unscaled_H0_test))[:10])

evaluation(y_test = Y_b01_unscaled_H0_test,
           y_pred = clf_pl.predict(X_b01_unscaled_H0_test),
           filename_csv = folderpath_results + "svm_rbf_H0_unscaled.csv")

Accuracy SVM : 0.56338028
Confusion-Matrix:
 [[15 18]
 [13 25]] 
 
True Negative:  15 
True Positive 25 
False Negative 13 
False Positive 18

TPR: 0.6578947368421053 
TNR:  0.45454545454545453

Accuracy: 0.5633802816901409
F1 (micro): 0.5633802816901409
F1 (macro): 0.5545436146529042


In [33]:
# RBF - H1 - unscaled
clf_pl_rbf = make_pipeline(StandardScaler(), 
                    SVC(kernel='rbf')).fit(X_b01_unscaled_H1_train, Y_b01_unscaled_H1_train)

print("Accuracy SVM : " + str(clf_pl_rbf.score(X_b01_unscaled_H1_test, Y_b01_unscaled_H1_test))[:10])

evaluation(y_test = Y_b01_unscaled_H1_test,
           y_pred = clf_pl_rbf.predict(X_b01_unscaled_H1_test),
           filename_csv = folderpath_results + "svm_rbf_H1_unscaled.csv")

Accuracy SVM : 0.56338028
Confusion-Matrix:
 [[12 27]
 [ 4 28]] 
 
True Negative:  12 
True Positive 28 
False Negative 4 
False Positive 27

TPR: 0.875 
TNR:  0.3076923076923077

Accuracy: 0.5633802816901409
F1 (micro): 0.5633802816901409
F1 (macro): 0.5400208986415883
